
import Conexiones.Conexion;
import static com.sun.javafx.animation.TickCalculation.sub;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.JOptionPane.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.*; //Para manejar los eventos
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.beans.binding.Bindings.and;

import javax.swing.*; //Para utilizar los componentes visuales de swing .
import static javax.swing.JOptionPane.showMessageDialog;

 
/**
 *
 * @author lwaw
 */
public class Login extends javax.swing.JFrame {

     Conexion con=new Conexion();
    Connection cn= con.Conexion();
     ResultSet Resultado;
     Statement sentencia;
    
   
    public Login() {
        initComponents();
      meter();
      combo_nombre();
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id_Usuario = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIngreso = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Pass = new javax.swing.JTextField();
        Usu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Id_Usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id Usuario", " " }));
        Id_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Id_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 160, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 44, 100, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        txtIngreso.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Downloads\\candado.png")); // NOI18N
        txtIngreso.setText("Ingresar");
        txtIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 190, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));
        getContentPane().add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 160, 30));
        getContentPane().add(Usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 610, 420));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String ik="C:\\Users\\dell\\Documents\\semestre 8\\ING. SOFTWARE\\VoltaGym\\src\\Imagenes\\candado.png";
        
        JOptionPane.showMessageDialog(rootPane, "CREADO POR: \n Brayan \n Eduardo \n Diana\n Hanna","VOLTA GYM", WIDTH,null);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresoActionPerformed
      ingresar();
    }//GEN-LAST:event_txtIngresoActionPerformed

    private void Id_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_UsuarioActionPerformed

      public void combo_nombre(){
        DefaultComboBoxModel combo;
        combo =new DefaultComboBoxModel();
        try {
            sentencia =cn.createStatement();
            Resultado=sentencia.executeQuery("SELECT  idCrear_Usuarios FROM crear_Usuarios");
            while(Resultado.next()){
                combo.addElement(Resultado.getString("idCrear_Usuarios"));
            }//
         Id_Usuario.setModel(combo);
            
        } catch (SQLException S) {
            showMessageDialog(null, "ocurrio un error");
        }
    }//----------------------llenado del id se los usuarios
    
    
    public  void meter(){
        txtIngreso.setText("Ingresar");
txtIngreso.setIcon(new ImageIcon("C:\\Users\\dell\\Documents\\semestre 8\\ING. SOFTWARE\\VoltaGym\\src\\Imagenes\\candado.png"));


txtIngreso.setVerticalTextPosition(SwingConstants.TOP);
       
    }
    
    public void ingresar(){
        enviarid();
                 String cap="";  
        String U=Usu.getText();
        String P=Pass.getText();
        String I=Id_Usuario.getSelectedItem().toString();
        
        con.Conexion();
        String SQL="select  * from crear_usuarios"
                + " where Nombre_Usuarios='"+U+"'&& Password_Usuarios='"+P+"'";
        
         try {
             sentencia=cn.createStatement();
                Resultado=sentencia.executeQuery(SQL);
                
                while (Resultado.next()){
                    cap=Resultado.getString("Tipo");
                   
                    if(cap.equals("Administrador")){
                        String k=cap;
                        MenuPrincipal menu= new MenuPrincipal();
                        menu.Usuario.setText(k);
                        MenuPrincipal.ID.setText(I);
                        
                       Productos nProductos=new Productos();
                       nProductos.setVisible(true);
                
                        dispose();
                   }//fin del; if  admnistrador
                      if(cap.equals("Cajero")){
                             String k=cap;
                             
                        MenuPrincipal_Cajero menuc= new MenuPrincipal_Cajero();
                        menuc.Usuario.setText(k);
                        enviarid();
                       Productos nProductos=new Productos();
                       nProductos.setVisible(true);
                
                        JOptionPane.showMessageDialog(null,"Bienvenido "+ cap);
                        dispose();
                   }//fin del; if 
                    
                  
                          
                    if((!cap.equals("Administrador")) && (!cap.equals("Cajero"))){
                        JOptionPane.showMessageDialog(null,"usuario no encontrado");
                    }
                }//fin del whilw
         } catch (SQLException ex) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
             
         }
       }//-----------------------------------------------------------------------ingresar
    
     public void enviarid(){
         String caja=Usu.getText();
        String SQL ="SELECT idCrear_Usuarios from crear_usuarios where Nombre_Usuarios='"+caja+"'";
         String Cap;
         MenuPrincipal menu=new MenuPrincipal();
         try {
                sentencia =cn.createStatement();
            Resultado=sentencia.executeQuery(SQL);
            while(Resultado.next()){
                showMessageDialog(null,"Bienvenodo");
              //  menu.IDS.setText(Resultado.getString("idCrear_Usuarios"));
            }
                 String n;
                n = Resultado.toString();
                menu.IDS.setText(n);
                 showMessageDialog(null, n);
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                showMessageDialog(null, "no se pudo completar la consulta");
            }
             
             
                     
         } 
        
        
        
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Id_Usuario;
    private javax.swing.JTextField Pass;
    private javax.swing.JTextField Usu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton txtIngreso;
    // End of variables declaration//GEN-END:variables
}
