/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lwaw
 */
public class MenuPrincipal_Cajero extends javax.swing.JFrame {

   
    public MenuPrincipal_Cajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();
        lblMembresia = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(120, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setText("jLabel1");
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblProductosMousePressed(evt);
            }
        });
        getContentPane().add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 300, 200));

        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVentasMousePressed(evt);
            }
        });
        getContentPane().add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 300, 200));

        lblMembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMembresiaMousePressed(evt);
            }
        });
        getContentPane().add(lblMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 300, 200));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero.jpeg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMousePressed
        Productos productos=new Productos();
        productos.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblProductosMousePressed

    private void lblVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMousePressed
        int seleccion=Integer.parseInt( javax.swing.JOptionPane.showInputDialog("ingrese su Opcion\n"
            + "1 : Ventas Membresias\n "
            + "2: Ventas Productos"));
    if(seleccion==1){
        Ventas_membresias ventas_membresias=new  Ventas_membresias();
        ventas_membresias.setVisible(true);
        this.dispose();

        }
        if(seleccion==2){
            Ventas_productos ventas_productos=new Ventas_productos();
            ventas_productos.setVisible(true);
            this.dispose();

        }
        else {
            javax.swing.JOptionPane.showMessageDialog(null,"ësta opcion no esta disponible");

        }

    }//GEN-LAST:event_lblVentasMousePressed

    private void lblMembresiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMembresiaMousePressed
        Membresia membresia=new  Membresia();
        membresia.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblMembresiaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal_Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Usuario;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblVentas;
    // End of variables declaration//GEN-END:variables
}
